#!/usr/bin/env python3

import argparse
import sys

import c

parser = argparse.ArgumentParser()
parser.add_argument('filename_csv')
args = parser.parse_args()

GENERATED_NOTE = (
    '//Generated with the command\n//    {com}'
).format(com=' '.join(sys.argv))

if __name__ == '__main__':
    #Getting some constants so I don't have to both with dynamic allocation in
    #the C code.
    with open(args.filename_csv, 'r') as f:
        csv_length = 0
        max_line_length = 0
        max_name_length = 0
        for line in filter(lambda line: not line.startswith('#'), f):
            csv_length += 1
            max_line_length = max(max_line_length, len(line))
            max_name_length = max(max_name_length, len(line.split('\t')[-1]))
    macros = [
        c.Macro('FILENAME_CSV', '"{fil}"'.format(fil=args.filename_csv)),
        c.Macro('CSV_LENGTH', csv_length),
        c.Macro('MAX_LINE_LENGTH', max_line_length),
        c.Macro('MAX_NAME_LENGTH', max_name_length),
    ]
    guard = c.IncludeGuard(args.filename_csv)
    sys.stdout.write('\n'.join(map(str, [
        guard.begin(), GENERATED_NOTE, *macros, guard.end()
    ])))
