#!/usr/bin/env python3

import argparse
import functools
import operator
import sys

parser = argparse.ArgumentParser()
parser.add_argument('filename_common_words')
parser.add_argument('filename_dictionary')
args = parser.parse_args()

with open(args.filename_common_words, 'r') as f:
    common = set(map(lambda line: line.strip().upper(), f))

with open(args.filename_dictionary, 'r') as f:
    sys.stdout.write(''.join(filter(
        lambda line: line.startswith(';;;') or line.split()[0] in common, f
    )))
